# deploy.yml
name: Deploy to GitHub Pages

on:
  # 当你向 main 分支推送代码时触发
  push:
    branches:
      - main
  # 允许你手动在 Actions 标签页中触发此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # 这个 job 负责构建你的网站
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 我们只需要一个确定的 Node.js 版本来构建
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Astro site
        run: npm run build # 运行构建命令
      - name: Upload build artifact
        # ↓↓↓ 这是关键步骤之一：将构建好的 dist 文件夹打包上传，供下一步使用
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # 这个 job 负责将上一步构建好的网站部署出去
  deploy:
    needs: build # 依赖于 build job 成功完成
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        # ↓↓↓ 这是另一个关键步骤：使用官方的 action 来进行部署
        id: deployment
        uses: actions/deploy-pages@v4